if(EXISTS "/var/home/bazzite/ドキュメント/src/nkCryptoTool/build_final/unit_tests[1]_tests.cmake")
  include("/var/home/bazzite/ドキュメント/src/nkCryptoTool/build_final/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
